data_dir: ./data/fairness/fairness_data/
prompt_file: adult_0_8.jsonl
gt_file: gt_labels_adult_0_8.npy
sensitive_attr_file: sensitive_attr_adult_0_8.npy
dataset: adult
out_file: ./data/fairness/results/${model}/test.json