template: 0
data_file: ./data/toxicity/user_prompts/nontoxic.jsonl
out_file: ./data/toxicity/user_prompts/generations/${model}/nontoxic-template-${.template}-generations.jsonl
max_tokens: 150
n: 1
t: 1
save_interval: 100
