# Toxicity
dt-run --config-name config --multirun +model_config=hf +toxicity=realtoxicityprompts-nontoxic-adv,realtoxicityprompts-nontoxic,realtoxicityprompts-toxic-adv,realtoxicityprompts-toxic,toxic-gpt3.5-adv,toxic-gpt3.5,toxic-gpt4-adv,toxic-gpt4

# Stereotype and bias
dt-run --config-name config --multirun +model_config=hf +stereotype=benign,targeted,untargeted

# Adversarial robustness
dt-run --config-name config --multirun +model_config=hf +advglue=alpaca,benign,stable-vicuna,vicuna

# Out-of-Distribution Robustness
dt-run --config-name config --multirun +model_config=hf +ood=knowledge_2020_5shot,knowledge_idk,knowledge_standard,style_8shot,style

# Privacy
dt-run --config-name config --multirun +model_config=hf +privacy=email_extraction_context100,email_extraction_context200,email_extraction_context50,email_extraction_known_fiveshot_a,email_extraction_known_fiveshot_b,email_extraction_known_fiveshot_c,email_extraction_known_fiveshot_d,email_extraction_known_oneshot_a,email_extraction_known_oneshot_b,email_extraction_known_oneshot_c,email_extraction_known_oneshot_d,email_extraction_known_zeroshot_a,email_extraction_known_zeroshot_b,email_extraction_known_zeroshot_c,email_extraction_known_zeroshot_d,email_extraction_unknown_fiveshot_a,email_extraction_unknown_fiveshot_b,email_extraction_unknown_fiveshot_c,email_extraction_unknown_fiveshot_d,email_extraction_unknown_oneshot_a,email_extraction_unknown_oneshot_b,email_extraction_unknown_oneshot_c,email_extraction_unknown_oneshot_d,email_extraction_unknown_zeroshot_a,email_extraction_unknown_zeroshot_b,email_extraction_unknown_zeroshot_c,email_extraction_unknown_zeroshot_d,pii_fewshot_attack,pii_fewshot_protect,pii_zeroshot,understanding_q1,understanding_q2,understanding_q3

# Robustness to Adversarial Demonstrations
dt-run --config-name config --multirun +model_config=hf +adv_demonstration=backdoor_exp1_addsent_setup1,backdoor_exp1_addsent_setup2,backdoor_exp1_addsent_setup3,backdoor_exp1_badword_setup1,backdoor_exp1_badword_setup2,backdoor_exp1_badword_setup3,backdoor_exp1_stylebkd_setup1,backdoor_exp1_stylebkd_setup2,backdoor_exp1_stylebkd_setup3,backdoor_exp1_synbkd_setup1,backdoor_exp1_synbkd_setup2,backdoor_exp1_synbkd_setup3,counterfactual_control_raising_cf,counterfactual_control_raising,counterfactual_irregular_form_cf,counterfactual_irregular_form,counterfactual_main_verb_cf,counterfactual_main_verb,counterfactual_snli_hypothesis_cf,counterfactual_snli_hypothesis,counterfactual_snli_premise_cf,counterfactual_snli_premise,counterfactual_syntactic_category_cf,counterfactual_syntactic_category,spurious_adverb_entail-bias,spurious_adverb_non-entail-bias,spurious_adverb_zero,spurious_embedded_under_verb_entail-bias,spurious_embedded_under_verb_non-entail-bias,spurious_embedded_under_verb_zero,spurious_l_relative_clause_entail-bias,spurious_l_relative_clause_non-entail-bias,spurious_l_relative_clause_zero,spurious_passive_entail-bias,spurious_passive_non-entail-bias,spurious_passive_zero,spurious_PP_entail-bias,spurious_PP_non-entail-bias,spurious_PP_zero,spurious_s_relative_clause_entail-bias,spurious_s_relative_clause_non-entail-bias,spurious_s_relative_clause_zero

# Machine Ethics
bash scripts/hf_example/ethics.sh hf

# Fairness
dt-run --config-name config --multirun +model_config=hf +fairness=crime_br_0.0,crime_br_0.5,crime_br_1.0,few_shot_0_fair_demon,few_shot_16_fair_demon,few_shot_32_fair_demon,few_shot_tr_br_0.0,few_shot_tr_br_0.5,few_shot_tr_br_1.0,zero_shot_br_0.0,zero_shot_br_0.5,zero_shot_br_1.0
