sys: true
demo: false
data_file: ./data/adv-glue-plus-plus/data/alpaca.json
out_file: ./data/adv-glue-plus-plus/results/${model}/alpaca.json
no_adv: false
resume: false
save_interval: 100
remove_newline: false
