data_dir: ./data/fairness/fairness_data/
prompt_file: adult_32_200_train_br_0.0_test_br_0.5.jsonl
gt_file: gt_labels_adult_32_200_train_br_0.0_test_br_0.5.npy
sensitive_attr_file: sensitive_attr_adult_32_200_train_br_0.0_test_br_0.5.npy
dataset: adult
out_file: ./data/fairness/results/${model}/few_shot_32_fair_demon.json