key: null
dry_run: False

defaults:
  - _self_
  - override hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN
  job:
    chdir: false
  launcher:
    # @package hydra.launcher
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    submitit_folder: ./logs/${hydra.sweep.dir}/.submitit/%j
    timeout_min: 720
    cpus_per_task: 12
    gpus_per_task: 1
    tasks_per_node: 1
    mem_gb: 62
    nodes: 1
    gres: gpu:1
    name: ${hydra.job.name}
    partition: compute
    comment: null
    signal_delay_s: 120
    max_num_timeout: 0
    additional_parameters: { }
    array_parallelism: 256
    setup: null
