data_file: ./data/ood/knowledge.json
out_file: ./results/ood/results/${model_config.model}/knowledge_idk.json
result_file: ./results/ood/results/${model_config.model}/final_scores.json
few_shot_num: 0
task: knowledge
idk: True
resume: False
save_interval: 100