sys: true
demo: false
data_file: ./data/adv-glue-plus-plus/data/alpaca.json
out_file: ./results/adv-glue-plus-plus/${model}/alpaca.json
no_adv: false
resume: false
save_interval: 100
remove_newline: false
task: ["sst2", "qqp", "mnli"]
