sys: false
demo: true
data_file: null
out_file: ./results/adv-glue-plus-plus/${model_config.model}/glue-benign-demo.json
no_adv: true
resume: false
save_interval: 100
remove_newline: false
task: ["sst2", "qqp", "mnli"]
